import Head from "next/head";
import styles from "../styles/Home.module.css";
import Cube from "./components/cube";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Speed Cubing App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <header>
          <h1>Successfully logged in.</h1>
        </header>
        <Cube />
      </div>
    </div>
  );
}
