import Head from "next/head";
import React, { useState } from "react";
import { Magic } from "magic-sdk";
import Router from "next/router";

export default function Login() {
  const [email, setEmail] = useState("");
  const [error, setError] = useState(null);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError(null);
    const magic = new Magic(process.env.NEXT_PUBLIC_MAGIC_PUBLISHABLE_KEY);
    const didToken = await magic.auth.loginWithMagicLink({ email });
    const res = await fetch("/api/login", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: "Bearer " + didToken,
      },
      body: JSON.stringify({ email }),
    });
    if (res.status === 200) {
      Router.push("/");
    } else {
      setError("Unsuccessful");
    }
  };

  return (
    <div>
      <Head>
        <title>Speed Cubing App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>Speed Cubing App</h1>
      </header>
      <form onSubmit={handleSubmit}>
        <p>Please sign in.</p>
        <div>
          <label htmlFor="email">Email</label>
          <input id="email" type="text" value={email} onChange={(e) => setEmail(e.target.value)} />
        </div>
        <button>Login in/Sign up</button>
      </form>
      {error && <p>{error}</p>}
    </div>
  );
}
